### ISSUE TITLE
Auth with server?

### ISSUE THREAD

**Issue by samueljim** [larsdecker/gridfs-promise#1]
I can't login to the server 

```
const MongoClientOptions = {
  autoReconnect: true,
};

const gridFS = new GridFSPromise.GridFSPromise('mongodb://user:password@ds1234567.mlab.com:29386', 'server', MongoClientOptions, 'images', __dirname + './output');
```
`
error code 

```
{"name":"MongoError","message":"Authentication failed.","ok":0,"errmsg":"Authentication failed.","code":18,"codeName":"AuthenticationFailed"}
```

**Comment by larsdecker** [comment]
Thank you for the report. I will check it and give you feedback.

**Comment by larsdecker** [comment]
I use the normal MongoClient for the Connection that are describe here: http://mongodb.github.io/node-mongodb-native/3.0/api/MongoClient.html#.connect

I have tested it with a url encoded mongo connection without the auth problem.

`const gridFSPromise = new GridFSPromise("mongodb://test:<passwordHere>@ds11912x.mlab.com:19129/my-gridfs-test",
                            "my-gridfs-test", {
                                            autoReconnect: true,
                                        },
                            "attachments", `${__dirname}/../cache`);`
