### ISSUE TITLE
README.md has the same example for uploadFileString as for getObject

### ISSUE THREAD

**Issue by FajsiEx** [larsdecker/gridfs-promise#6]
![image](https://user-images.githubusercontent.com/32551223/99714553-03b40800-2aa6-11eb-8a25-f5fa143b339e.png)

I would like to use your library, but I don't see how does the `uploadFileString` method works...

**Comment by larsdecker** [comment]
Yes that is right. Sorry for the late reply.

I have added some example code for it.
